config/routes.rb
Rails.application.routes.draw do
  resources :categories
  devise_for :users
  root 'blogs#index'
  resources :blogs do
  resources :comments
  resources :comments do
  resources :replies
  end
  end
  #root 'blogs#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blog.rb
class Blog < ApplicationRecord
  has_many :comments, dependent: :destroy
  has_many :images, dependent: :destroy
  validates :title, presence: true,
                    length: { minimum: 5 }
  mount_uploader :image, AvatarUploader
  mount_uploader :video, AvatarUploader
end

app/models/category.rb
class Category < ApplicationRecord
	# has_many :blogs, :foreign_key =>"category_id" , :class_name => "blog"
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :blog
  has_many :replies, dependent: :destroy
end

app/models/image.rb
class Image < ApplicationRecord
  belongs_to :blog
  mount_uploader :image, AvatarUploader
end

app/models/reply.rb
class Reply < ApplicationRecord
  belongs_to :comment
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
before_action :authenticate_user!, except: [:index, :show]
	def index
   if params[:search].present?
        @blogs = Blog.where('title LIKE ? OR description LIKE ?', "%#{params[:search]}%",
        "%#{params[:search]}%")
      elsif params[:start_date].present? && params[:end_date].present?
      @blogs = Blog.where('created_at >= ? AND created_at <=?',
      params[:start_date].to_date, params[:end_date].to_date) 
      else 
        @blogs = Blog.all 
     end
  end

	 def show
    @blog = Blog.find(params[:id])
  end

def new
  @blog = Blog.new
end
 
 def edit
  @blog = Blog.find(params[:id])
end

def create
  @blog = Blog.new(blog_params)
  if @blog.save
   params[:blog][:image].each do |image|
   Image.create(:image=> image, blog_id: @blog.id)
  end
    redirect_to @blog
  else
    render 'new'
  end
end
 
 def update
  @blog = Blog.find(params[:id])
  if @blog.update(blog_params)
     # images = Image.where(:article_id=>@article.id)
     images = @blog.images
     if params[:blog][:image].present?
       images.destroy_all
       params[:blog][:image].each do |image|
       Image.create(:image=> image, blog_id: @blog.id)
     end
   end
    redirect_to @blog
  else
    render 'edit'
  end
end

def destroy
    @blog = Blog.find(params[:id])
    @blog.destroy
 
    redirect_to blogs_path
  end

private
  def blog_params
    params.require(:blog).permit(:title, :description, :image, :video, :category_id)
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :edit, :update, :destroy]

  # GET /categories
  # GET /categories.json
  def index
    @categories = Category.all
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: 'Category was successfully created.' }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1
  # PATCH/PUT /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to @category, notice: 'Category was successfully updated.' }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to categories_url, notice: 'Category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def category_params
      params.require(:category).permit(:name, :description)
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
 
	def create
    @blog = Blog.find(params[:blog_id])
    @comment = @blog.comments.create(comment_params)
    # redirect_to blog_path(@blog)
    render 'blogs/create_comments'
  end

def edit
    @blog= Blog.find(params[:blog_id])
    @comment = @blog.comments.find(params[:id])
  end

   def update
    @blog = Blog.find(params[:blog_id])
    @comment = @blog.comments.find(params[:id])

    if @comment.update(comment_params)
      redirect_to blog_path(@blog)
    else
      render 'edit'
    end
  end
  
 def destroy
    @blog = Blog.find(params[:blog_id])
    @comment = @blog.comments.find(params[:id])
    @comment.destroy
    redirect_to blog_path(@blog)
  end
 
  private
    def comment_params
      params.require(:comment).permit(:commenter, :body)
    end
end

app/controllers/replies_controller.rb
class RepliesController < ApplicationController
	before_action do
    @comment = Comment.find(params[:comment_id])
  end

  def index
    @replies = @comment.replies
    @reply = @comment.replies.new
  end

  def new
    @reply = @comment.replies.new
  end

  def create
 
    @reply =  Reply.new(:body=>params[:reply][:body],:comment_id=>params[:reply][:comment_id])
    @reply.save
    @replies= Reply.where(:comment_id=> params[:reply][:comment_id])
    flash[:notice]= "replies created"

     # redirect_to "/blogs/#{params[:blog_id]}"
    #redirect somewhere
     render 'blogs/create_replies'
end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/replies_helper.rb
module RepliesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/blogs/_form.html.erb
<%= form_for @blog do |f| %>
 
  <% if @blog.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@blog.errors.count, "error") %> prohibited
        this blog from being saved:
      </h2>
      <ul>
        <% @blog.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
 
  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>
 
  <p>
    <%= f.label :description %><br>
    <%= f.text_area :description%>
  </p>
 <p>
    <%= f.label :image %><br>
    <%= f.file_field :image, :multiple=>true%>
  </p>
  <p>
    <%= f.label :video %><br>
    <%= f.file_field :video%>
  </p>
  <p>
    <%= f.select(:category_id, Category.all.collect {|u| [u.name, u.id]}, :prompt => 'Select Category') %>
    
  </p>
  <p>
    <%= f.submit %>
  </p>
 
<% end %>

app/views/blogs/create_comments.js.erb
$('.comments-container').html('<%= escape_javascript( render "comments/comments")%>');
$("#new_comment")[0].reset();
$("#new_comment").hide();

app/views/blogs/create_replies.js.erb
$('.replies-container_<%= params[:reply][:comment_id] %>').html('<%= escape_javascript( render "replies/replies")%>');
$("#reply_body")[0].reset();
$("#reply_body").hide();

app/views/blogs/edit.html.erb
<h1>Edit blog</h1>
 
<%= render 'form' %>
 
<%= link_to 'Back', blogs_path %>

app/views/blogs/index.html.erb
  <% if params[:search].present? %>
   <%= @blogs.count %> Results found.
   <% else %>
   no result found
  <% end %>
<h1>Listing blogs</h1>
 <%= link_to 'New blog', new_blog_path %>
<table>
  <tr>
    <th>Title</th>
    <th>Description</th>
    <th>Category</th>
    <th>Image</th>
     <th>Video</th>
   <th colspan="6"></th>
  </tr>
 
  <% @blogs.each do |blog| %>
    <tr>
      <td><%= blog.title %></td>
      <td><%= blog.description %></td>
      <td>  
      <%if blog.category_id.present? %> 
      <%= Category.find(blog.category_id).name %>
      <% end %>
      </td> 
      <td><%  blog.images.each do |image| %>
      <%= image_tag image.image, :height=>"200", :width=>"200" %>
      <%end%></td>
      <td><%= video_tag blog.video, :controls=>true, :height=>"200", :width=>"400" %>
      </td>
      <td><%= link_to 'Show', blog_path(blog) %></td>
      <td><%= link_to 'Edit', edit_blog_path(blog) %></td>
      <td><%= link_to 'Destroy', blog_path(blog),
              method: :delete,
              data: { confirm: 'Are you sure?' } %></td>
     </tr>
  <% end %>
</table>

app/views/blogs/new.html.erb
<h1>New blog</h1>
 
<%= render 'form' %>
 
<%= link_to 'Back', blogs_path %>

app/views/blogs/show.html.erb
<p>
  <strong>Title:</strong>
  <%= @blog.title %>
</p>
 
<p>
  <strong>Description:</strong>
  <%= @blog.description %>
</p>
<p>
  <strong>Image:</strong>
  <%@blog.images.each do |image|%>
  <%= image_tag image.image, :height=>"200", :width=>"200" %>
  <%end%>
</p>
<p>
  <strong>Video:</strong>
  <%= video_tag @blog.video, :controls=>true, :height=>"200", :width=>"400" %>
</p>
<div class="comments-container">
<h2>Comments</h2>
<%= render 'comments/comments' %>
 </div>
<h2>Add a comment:</h2>
<%= render 'comments/form' %>
 
<%= link_to 'Edit', edit_blog_path(@blog) %> |
<%= link_to 'Back', blogs_path %>

app/views/categories/_form.html.erb
<%= form_for(category) do |f| %>
  <% if category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
      <% category.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :description %>
    <%= f.text_field :description %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<h1>Editing Category</h1>

<%= render 'form', category: @category %>

<%= link_to 'Show', @category %> |
<%= link_to 'Back', categories_path %>

app/views/categories/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Categories</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @categories.each do |category| %>
      <tr>
        <td><%= category.name %></td>
        <td><%= category.description %></td>
        <td><%= link_to 'Show', category %></td>
        <td><%= link_to 'Edit', edit_category_path(category) %></td>
        <td><%= link_to 'Destroy', category, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Category', new_category_path %>

app/views/categories/new.html.erb
<h1>New Category</h1>

<%= render 'form', category: @category %>

<%= link_to 'Back', categories_path %>

app/views/categories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @category.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @category.description %>
</p>

<%= link_to 'Edit', edit_category_path(@category) %> |
<%= link_to 'Back', categories_path %>

app/views/comments/_comment.html.erb
<p>
  <strong>Commenter:</strong>
  <%= comment.commenter %>
</p>
 
<p>
  <strong>Comment:</strong>
  <%= comment.body %>
</p>
<p>
  <%= link_to 'Destroy Comment', [comment.blog, comment],
               method: :delete,
               data: { confirm: 'Are you sure?' } %>
</p>
<p>
  <%= link_to 'Edit Comment', edit_blog_comment_path(comment.blog, comment) %>
</p>

<h2> reply a comment</h2>
<% @replies= Reply.where(:comment_id=> comment.id)
%>

<%@replies.each do |reply|%>
  <p>
  <strong>Reply:</strong>
  <%=reply.body%></p>
<%end%>
<%= render 'replies/form', :comment=>comment %>

app/views/comments/_comments.html.erb
<% @blog.comments.each do |comment|%>

<p>
  <strong>Commenter:</strong>
  <%= comment.commenter %>
</p>
 
<p>
  <strong>Comment:</strong>
  <%= comment.body %>
</p>
<p>
  <%= link_to 'Destroy Comment', [comment.blog, comment],
               method: :delete,
               data: { confirm: 'Are you sure?' } %>
</p>
<p>
  <%= link_to 'Edit Comment', edit_blog_comment_path(comment.blog, comment) %>
</p>

<h2> reply a comment</h2>

<% @replies= Reply.where(:comment_id=> comment.id)
%>
<div class="replies-container_<%= comment.id %>">
<%= render 'replies/replies' %>
</div>
<%= render 'replies/form', :comment=>comment %>

<% end %>

app/views/comments/_form.html.erb
<%= form_for([@blog, @blog.comments.build], :remote=>true) do |f| %>
  <p>
    <%= f.label :commenter %><br>
    <%= f.text_field :commenter %>
  </p>
  <p>
    <%= f.label :body %><br>
    <%= f.text_area :body %>
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/comments/edit.html.erb
<h1>Edit comment</h1>
<%= form_for([@blog, @comment], :method=>"patch") do |f| %>
  <p>
    <%= f.label :commenter %><br>
    <%= f.text_field :commenter %>
  </p>
  <p>
    <%= f.label :body %><br>
    <%= f.text_area :body %>
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end %>
 
<%= link_to 'Back', blogs_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Home</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
   <body>
    <div id="user_nav">
    <% if user_signed_in? %> 
    Signed in as 
    <%= current_user.email %>. Not you? 
    <%= link_to "Sign out", destroy_user_session_path, :method => :delete %> 
    <%=form_tag "/blogs" ,:method=>"GET" do %> 
    <%= text_field_tag :search, params[:search] , :placeholder => "Type here to search"%> 
    <%= text_field_tag :start_date, params[:start_date] , :placeholder => "Start date", :id=>"start-date"%>
     <%= text_field_tag :end_date, params[:end_date] , :placeholder => "end_date" , :id=>"end-date"%> 
     <%= submit_tag "Search", :class=>"btn btn-primary"%> 
     <%end%>
      <% else %>
       <%= link_to "Sign up", new_user_registration_path %> or
        <%= link_to "sign in", new_user_session_path %> 
        <% end %>   
        </div> 
      <%= yield %>
    </body>
  </html>
<script> 
  $( function() { 
    $("#start-date" ).datepicker({ dateFormat: 'dd-mm-yy' }); 
    $("#end-date" ).datepicker({ dateFormat: 'dd-mm-yy' }); 
  } ); 
  </script>

app/views/replies/_form.html.erb
<%= form_for :reply, url: "/blogs/#{@blog.id}/comments/#{comment.id}/replies", :remote=>true do |f| %>
   <%= f.hidden_field :comment_id,  :value=> comment.id %>
   <%= f.text_field :body %>
   <%= f.submit %>
<% end %>

app/views/replies/_replies.html.erb
<%@replies.each do |reply|%>
  <p>
  <strong>Reply:</strong>
  <%=reply.body%></p>
<%end%>

app/views/welcome/index.html.erb
<h1>Hello, Rails!</h1>
<%= link_to 'My Blog', controller: 'blogs' %>